public class tryApex {
    
    public static void check()
    {
        Account c = tryApex.ex(true);
        if(c != null){
            System.debug('Not a Null10ss');
        }else{
            System.debug('Yes NULLi');
        }
            
    }
    
    public static  Account ex(Boolean a){
        Account abc;
        
        if(a){ 
            abc = new Account();
            return abc;
        }
    return abc;
    }
}
//List Exception